# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-19 08:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PresenceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('present', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SchoolSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('teacher_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('school_class', models.IntegerField(choices=[(1, '1a'), (2, '1b'), (3, '2a'), (4, '2b'), (5, '3a'), (6, '3b')])),
                ('year_of_birth', models.IntegerField(null=True, validators=[None])),
            ],
        ),
        migrations.CreateModel(
            name='StudentGrades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(choices=[(1, '1'), (1.5, '1+'), (1.75, '2-'), (2, '2'), (2.5, '2+'), (2.75, '3-'), (3, '3'), (3.5, '3+'), (3.75, '4-'), (4, '4'), (4.5, '4+'), (4.75, '5-'), (5, '5'), (5.5, '5+'), (5.75, '6-'), (6, '6')])),
                ('school_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adv.SchoolSubject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adv.Student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('from_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adv.SchoolSubject')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adv.Student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='grades',
            field=models.ManyToManyField(through='adv.StudentGrades', to='adv.SchoolSubject'),
        ),
        migrations.AddField(
            model_name='presencelist',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adv.Student'),
        ),
        migrations.AddField(
            model_name='message',
            name='from_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adv.Student'),
        ),
        migrations.AddField(
            model_name='message',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adv.SchoolSubject'),
        ),
    ]
