# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-19 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year_of_birth',
            field=models.IntegerField(null=True),
        ),
    ]
